# Site settings
title: mentats.github.io
email:
description: > # this means to ignore newlines until "baseurl:"
  A blog about Remedy / ITSM and SQL snippets, electric bass, #! and bad grammar. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mentats.github.io" # the base hostname & protocol for your site
twitter_username: jmfragadv
github_username:  mentats

# Build settings
markdown: kramdown
